In [1]:
import pandas as pd
import ast
from random import randint
df = pd.read_csv("dataset.csv")

In [2]:
df

,productId,productImage,brand,title,description,packageSizing,mopDeal,pcoDeal,inventoryIndicator,offerType,...,deal,inventoryIndicator.indicatorId,inventoryIndicator.text,pricing.environmentalHandlingFee.carbonFee,pricing.environmentalHandlingFee.ecologyFee,pricing.environmentalHandlingFee.electronicFee,pricing.environmentalHandlingFee.hazardousFee,productBadge.badgeId,productBadge.badgeClass,productBadge.text
0,20091825001_EA,[{'imageUrl': 'https://assets.shop.loblaws.ca/...,NaN,Cilantro,Cilantro is the bunched leafy green from the c...,"1 ea, $0.97/1ea",NaN,NaN,NaN,OG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20143381001_KG,[{'imageUrl': 'https://assets.shop.loblaws.ca/...,NaN,Roma Tomatoes,Roma (or plum) tomatoes are egg-shaped and na...,$5.49/1kg $2.49/1lb,NaN,NaN,NaN,OG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20179038001_KG,[{'imageUrl': 'https://assets.shop.loblaws.ca/...,NaN,Ginger,Ginger (or gingerroot) has a tough tan skin an...,$4.37/1kg $1.98/1lb,NaN,NaN,NaN,OG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21004355001_EA,[{'imageUrl': 'https://assets.shop.loblaws.ca/...,Rooster,"Garlic Bulbs, 3-count",<p>Don't forget to add Garlic Bulbs to your we...,"90 g, $0.29/1ea",NaN,NaN,NaN,OG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20135581001_KG,[{'imageUrl': 'https://assets.shop.loblaws.ca/...,NaN,Colossal Garlic,Garlic has a plump bulb (or head) of individua...,$12.10/1kg $5.49/1lb,NaN,NaN,NaN,OG,...,NaN,OUT,Out of Stock,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10027,20311560003_EA,[{'imageUrl': 'https://assets.shop.loblaws.ca/...,Paldo,"Bowl Noodle Soup, Hot & Spicy",NaN,"86 g, $1.49/100g",NaN,NaN,NaN,OG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10028,21088254_EA,[{'imageUrl': 'https://assets.shop.loblaws.ca/...,Frank's,Hot Buffalo Wings Sauce,Get hot & spicy restaurant-style wings at home...,"354 ml, $1.27/100ml",NaN,NaN,NaN,OG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10029,21003336_EA,[{'imageUrl': 'https://assets.shop.loblaws.ca/...,Charlotte's,"Cookies & Cream Cake 6""",NaN,"400 g, $1.75/100g",NaN,NaN,NaN,OG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10030,21283361_EA,[{'imageUrl': 'https://assets.shop.loblaws.ca/...,Farmer's Market,Muffins Double Chocolate,NaN,"570 g, $1.14/100g",NaN,NaN,NaN,OG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10031,20173399_EA,[{'imageUrl': 'https://assets.shop.loblaws.ca/...,Natracare,Panty Liners,Certified organic cotton cover. Plastic free....,"30 ea, $0.17/1ea",NaN,NaN,NaN,OG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10032 entries, 0 to 10031
Data columns (total 54 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   productId                                       10032 non-null  object
 1   productImage                                    10032 non-null  object
 2   brand                                           9529 non-null   object
 3   title                                           10032 non-null  object
 4   description                                     7381 non-null   object
 5   packageSizing                                   10032 non-null  object
 6   mopDeal                                         0 non-null      float64
 7   pcoDeal                                         418 non-null    object
 8   inventoryIndicator                              0 non-null      float64
 9   offerType                                       10032 non-null  object
 10  offerId                                         10032 non-null  object
 11  action                                          0 non-null      float64
 12  isVariant                                       10032 non-null  bool
 13  link                                            10032 non-null  object
 14  productVendor                                   0 non-null      float64
 15  productVariant                                  0 non-null      float64
 16  textBadge                                       1180 non-null   object
 17  variantTheme                                    0 non-null      float64
 18  articleNumber                                   10032 non-null  int64
 19  uom                                             10032 non-null  object
 20  sponsoredCreative                               0 non-null      float64
 21  isSponsored                                     10032 non-null  bool
 22  isComplementarySponsored                        10032 non-null  bool
 23  complementarySponsoredBadgeText                 0 non-null      float64
 24  productBadge                                    0 non-null      float64
 25  pricing.price                                   10032 non-null  float64
 26  pricing.wasPrice                                469 non-null    object
 27  pricing.displayPrice                            10032 non-null  object
 28  pricing.memberOnlyPrice                         17 non-null     float64
 29  pricing.mopDisplayPrice                         17 non-null     object
 30  pricing.ehfTotal                                766 non-null    float64
 31  pricing.environmentalHandlingFee                0 non-null      float64
 32  pricingUnits.type                               10032 non-null  object
 33  pricingUnits.unit                               10032 non-null  object
 34  pricingUnits.interval                           10032 non-null  int64
 35  pricingUnits.minOrderQuantity                   10032 non-null  int64
 36  pricingUnits.maxOrderQuantity                   10032 non-null  int64
 37  pricingUnits.weighted                           10032 non-null  bool
 38  deal.type                                       2864 non-null   object
 39  deal.text                                       2864 non-null   object
 40  deal.points                                     2864 non-null   float64
 41  deal.name                                       2864 non-null   object
 42  deal.expiryDate                                 2396 non-null   object
 43  deal.dealPrice                                  1851 non-null   float64
 44  deal                                            0 non-null      float64
 45  inventoryIndicator.indicatorId                  780 non-null    object
 46  inventoryIndicator.text                         780 non-null    object
 47  pricing.environmentalHandlingFee.carbonFee      255 non-null    float64
 48  pricing.environmentalHandlingFee.ecologyFee     766 non-null    float64
 49  pricing.environmentalHandlingFee.electronicFee  255 non-null    float64
 50  pricing.environmentalHandlingFee.hazardousFee   255 non-null    float64
 51  productBadge.badgeId                            610 non-null    object
 52  productBadge.badgeClass                         472 non-null    object
 53  productBadge.text                               610 non-null    object
dtypes: bool(4), float64(20), int64(4), object(26)
memory usage: 3.9+ MB

In [4]:
df_2 = df[["productId", "title", "description", "uom", "pricing.price"]]

In [5]:
def extract_image(row):
    try:
        image = ast.literal_eval(row["productImage"])[0]["imageUrl"]
    except:
        image = None
    return image

df_2["Image"] = df.apply(extract_image, axis=1)
df_2

/var/folders/hl/vccfl52n063b0cwksbjpykyw0000gn/T/ipykernel_45552/3237205402.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2["Image"] = df.apply(extract_image, axis=1)

,productId,title,description,uom,pricing.price,Image
0,20091825001_EA,Cilantro,Cilantro is the bunched leafy green from the c...,EA,0.75,https://assets.shop.loblaws.ca/products/200918...
1,20143381001_KG,Roma Tomatoes,Roma (or plum) tomatoes are egg-shaped and na...,KG,0.66,https://assets.shop.loblaws.ca/products/201433...
2,20179038001_KG,Ginger,Ginger (or gingerroot) has a tough tan skin an...,KG,0.92,https://assets.shop.loblaws.ca/products/201790...
3,21004355001_EA,"Garlic Bulbs, 3-count",<p>Don't forget to add Garlic Bulbs to your we...,EA,0.88,https://assets.shop.loblaws.ca/products/210043...
4,20135581001_KG,Colossal Garlic,Garlic has a plump bulb (or head) of individua...,KG,1.21,https://assets.shop.loblaws.ca/products/201355...
...,...,...,...,...,...,...
10027,20311560003_EA,"Bowl Noodle Soup, Hot & Spicy",NaN,EA,1.28,https://assets.shop.loblaws.ca/products/203115...
10028,21088254_EA,Hot Buffalo Wings Sauce,Get hot & spicy restaurant-style wings at home...,EA,4.49,https://assets.shop.loblaws.ca/products/210882...
10029,21003336_EA,"Cookies & Cream Cake 6""",NaN,EA,7.00,https://assets.shop.loblaws.ca/products/210033...
10030,21283361_EA,Muffins Double Chocolate,NaN,EA,4.97,https://assets.shop.loblaws.ca/products/212833...
10031,20173399_EA,Panty Liners,Certified organic cotton cover. Plastic free....,EA,4.99,https://assets.shop.loblaws.ca/products/201733...

In [6]:
df_2.to_csv("datasets/master.csv")

In [7]:
stores = ["Walmart","Zehrs","Freshco","Food Basics","Canadian Superstore","Farahs","No Frills"]

In [8]:
for store in stores:
    # Create a copy of df_2 to avoid modifying the original DataFrame
    df_3 = df_2.copy()
    df_3["Store"] = store
    discount_rate = randint(5,12)
    df_3["pricing.price"] = round(df_3["pricing.price"] - df_3["pricing.price"] * discount_rate / 100, 2)
    df_3.to_csv(f"datasets/{store}.csv")
    print(df_3)
    del df_3

            productId                          title  \
0      20091825001_EA                       Cilantro
1      20143381001_KG                  Roma Tomatoes
2      20179038001_KG                         Ginger
3      21004355001_EA          Garlic Bulbs, 3-count
4      20135581001_KG                Colossal Garlic
...               ...                            ...
10027  20311560003_EA  Bowl Noodle Soup, Hot & Spicy
10028     21088254_EA        Hot Buffalo Wings Sauce
10029     21003336_EA        Cookies & Cream Cake 6"
10030     21283361_EA   Muffins Double Chocolate
10031     20173399_EA                   Panty Liners

                                             description uom  pricing.price  \
0      Cilantro is the bunched leafy green from the c...  EA           0.71
1      Roma (or plum) tomatoes are egg-shaped  and na...  KG           0.63
2      Ginger (or gingerroot) has a tough tan skin an...  KG           0.87
3      <p>Don't forget to add Garlic Bulbs to your we...  EA           0.84
4      Garlic has a plump bulb (or head) of individua...  KG           1.15
...                                                  ...  ..            ...
10027                                                NaN  EA           1.22
10028  Get hot & spicy restaurant-style wings at home...  EA           4.27
10029                                                NaN  EA           6.65
10030                                                NaN  EA           4.72
10031  Certified organic cotton cover.  Plastic free....  EA           4.74

                                                   Image    Store
0      https://assets.shop.loblaws.ca/products/200918...  Walmart
1      https://assets.shop.loblaws.ca/products/201433...  Walmart
2      https://assets.shop.loblaws.ca/products/201790...  Walmart
3      https://assets.shop.loblaws.ca/products/210043...  Walmart
4      https://assets.shop.loblaws.ca/products/201355...  Walmart
...                                                  ...      ...
10027  https://assets.shop.loblaws.ca/products/203115...  Walmart
10028  https://assets.shop.loblaws.ca/products/210882...  Walmart
10029  https://assets.shop.loblaws.ca/products/210033...  Walmart
10030  https://assets.shop.loblaws.ca/products/212833...  Walmart
10031  https://assets.shop.loblaws.ca/products/201733...  Walmart

[10032 rows x 7 columns]
            productId                          title  \
0      20091825001_EA                       Cilantro
1      20143381001_KG                  Roma Tomatoes
2      20179038001_KG                         Ginger
3      21004355001_EA          Garlic Bulbs, 3-count
4      20135581001_KG                Colossal Garlic
...               ...                            ...
10027  20311560003_EA  Bowl Noodle Soup, Hot & Spicy
10028     21088254_EA        Hot Buffalo Wings Sauce
10029     21003336_EA        Cookies & Cream Cake 6"
10030     21283361_EA   Muffins Double Chocolate
10031     20173399_EA                   Panty Liners

                                             description uom  pricing.price  \
0      Cilantro is the bunched leafy green from the c...  EA           0.70
1      Roma (or plum) tomatoes are egg-shaped  and na...  KG           0.62
2      Ginger (or gingerroot) has a tough tan skin an...  KG           0.86
3      <p>Don't forget to add Garlic Bulbs to your we...  EA           0.83
4      Garlic has a plump bulb (or head) of individua...  KG           1.14
...                                                  ...  ..            ...
10027                                                NaN  EA           1.20
10028  Get hot & spicy restaurant-style wings at home...  EA           4.22
10029                                                NaN  EA           6.58
10030                                                NaN  EA           4.67
10031  Certified organic cotton cover.  Plastic free....  EA           4.69

                                                   Image  Store
0      https://assets.shop.loblaws.ca/products/200918...  Zehrs
1      https://assets.shop.loblaws.ca/products/201433...  Zehrs
2      https://assets.shop.loblaws.ca/products/201790...  Zehrs
3      https://assets.shop.loblaws.ca/products/210043...  Zehrs
4      https://assets.shop.loblaws.ca/products/201355...  Zehrs
...                                                  ...    ...
10027  https://assets.shop.loblaws.ca/products/203115...  Zehrs
10028  https://assets.shop.loblaws.ca/products/210882...  Zehrs
10029  https://assets.shop.loblaws.ca/products/210033...  Zehrs
10030  https://assets.shop.loblaws.ca/products/212833...  Zehrs
10031  https://assets.shop.loblaws.ca/products/201733...  Zehrs

[10032 rows x 7 columns]
            productId                          title  \
0      20091825001_EA                       Cilantro
1      20143381001_KG                  Roma Tomatoes
2      20179038001_KG                         Ginger
3      21004355001_EA          Garlic Bulbs, 3-count
4      20135581001_KG                Colossal Garlic
...               ...                            ...
10027  20311560003_EA  Bowl Noodle Soup, Hot & Spicy
10028     21088254_EA        Hot Buffalo Wings Sauce
10029     21003336_EA        Cookies & Cream Cake 6"
10030     21283361_EA   Muffins Double Chocolate
10031     20173399_EA                   Panty Liners

                                             description uom  pricing.price  \
0      Cilantro is the bunched leafy green from the c...  EA           0.70
1      Roma (or plum) tomatoes are egg-shaped  and na...  KG           0.61
2      Ginger (or gingerroot) has a tough tan skin an...  KG           0.86
3      <p>Don't forget to add Garlic Bulbs to your we...  EA           0.82
4      Garlic has a plump bulb (or head) of individua...  KG           1.13
...                                                  ...  ..            ...
10027                                                NaN  EA           1.19
10028  Get hot & spicy restaurant-style wings at home...  EA           4.18
10029                                                NaN  EA           6.51
10030                                                NaN  EA           4.62
10031  Certified organic cotton cover.  Plastic free....  EA           4.64

                                                   Image    Store
0      https://assets.shop.loblaws.ca/products/200918...  Freshco
1      https://assets.shop.loblaws.ca/products/201433...  Freshco
2      https://assets.shop.loblaws.ca/products/201790...  Freshco
3      https://assets.shop.loblaws.ca/products/210043...  Freshco
4      https://assets.shop.loblaws.ca/products/201355...  Freshco
...                                                  ...      ...
10027  https://assets.shop.loblaws.ca/products/203115...  Freshco
10028  https://assets.shop.loblaws.ca/products/210882...  Freshco
10029  https://assets.shop.loblaws.ca/products/210033...  Freshco
10030  https://assets.shop.loblaws.ca/products/212833...  Freshco
10031  https://assets.shop.loblaws.ca/products/201733...  Freshco

[10032 rows x 7 columns]
            productId                          title  \
0      20091825001_EA                       Cilantro
1      20143381001_KG                  Roma Tomatoes
2      20179038001_KG                         Ginger
3      21004355001_EA          Garlic Bulbs, 3-count
4      20135581001_KG                Colossal Garlic
...               ...                            ...
10027  20311560003_EA  Bowl Noodle Soup, Hot & Spicy
10028     21088254_EA        Hot Buffalo Wings Sauce
10029     21003336_EA        Cookies & Cream Cake 6"
10030     21283361_EA   Muffins Double Chocolate
10031     20173399_EA                   Panty Liners

                                             description uom  pricing.price  \
0      Cilantro is the bunched leafy green from the c...  EA           0.70
1      Roma (or plum) tomatoes are egg-shaped  and na...  KG           0.62
2      Ginger (or gingerroot) has a tough tan skin an...  KG           0.86
3      <p>Don't forget to add Garlic Bulbs to your we...  EA           0.83
4      Garlic has a plump bulb (or head) of individua...  KG           1.14
...                                                  ...  ..            ...
10027                                                NaN  EA           1.20
10028  Get hot & spicy restaurant-style wings at home...  EA           4.22
10029                                                NaN  EA           6.58
10030                                                NaN  EA           4.67
10031  Certified organic cotton cover.  Plastic free....  EA           4.69

                                                   Image        Store
0      https://assets.shop.loblaws.ca/products/200918...  Food Basics
1      https://assets.shop.loblaws.ca/products/201433...  Food Basics
2      https://assets.shop.loblaws.ca/products/201790...  Food Basics
3      https://assets.shop.loblaws.ca/products/210043...  Food Basics
4      https://assets.shop.loblaws.ca/products/201355...  Food Basics
...                                                  ...          ...
10027  https://assets.shop.loblaws.ca/products/203115...  Food Basics
10028  https://assets.shop.loblaws.ca/products/210882...  Food Basics
10029  https://assets.shop.loblaws.ca/products/210033...  Food Basics
10030  https://assets.shop.loblaws.ca/products/212833...  Food Basics
10031  https://assets.shop.loblaws.ca/products/201733...  Food Basics

[10032 rows x 7 columns]
            productId                          title  \
0      20091825001_EA                       Cilantro
1      20143381001_KG                  Roma Tomatoes
2      20179038001_KG                         Ginger
3      21004355001_EA          Garlic Bulbs, 3-count
4      20135581001_KG                Colossal Garlic
...               ...                            ...
10027  20311560003_EA  Bowl Noodle Soup, Hot & Spicy
10028     21088254_EA        Hot Buffalo Wings Sauce
10029     21003336_EA        Cookies & Cream Cake 6"
10030     21283361_EA   Muffins Double Chocolate
10031     20173399_EA                   Panty Liners

                                             description uom  pricing.price  \
0      Cilantro is the bunched leafy green from the c...  EA           0.67
1      Roma (or plum) tomatoes are egg-shaped  and na...  KG           0.59
2      Ginger (or gingerroot) has a tough tan skin an...  KG           0.82
3      <p>Don't forget to add Garlic Bulbs to your we...  EA           0.78
4      Garlic has a plump bulb (or head) of individua...  KG           1.08
...                                                  ...  ..            ...
10027                                                NaN  EA           1.14
10028  Get hot & spicy restaurant-style wings at home...  EA           4.00
10029                                                NaN  EA           6.23
10030                                                NaN  EA           4.42
10031  Certified organic cotton cover.  Plastic free....  EA           4.44

                                                   Image                Store
0      https://assets.shop.loblaws.ca/products/200918...  Canadian Superstore
1      https://assets.shop.loblaws.ca/products/201433...  Canadian Superstore
2      https://assets.shop.loblaws.ca/products/201790...  Canadian Superstore
3      https://assets.shop.loblaws.ca/products/210043...  Canadian Superstore
4      https://assets.shop.loblaws.ca/products/201355...  Canadian Superstore
...                                                  ...                  ...
10027  https://assets.shop.loblaws.ca/products/203115...  Canadian Superstore
10028  https://assets.shop.loblaws.ca/products/210882...  Canadian Superstore
10029  https://assets.shop.loblaws.ca/products/210033...  Canadian Superstore
10030  https://assets.shop.loblaws.ca/products/212833...  Canadian Superstore
10031  https://assets.shop.loblaws.ca/products/201733...  Canadian Superstore

[10032 rows x 7 columns]
            productId                          title  \
0      20091825001_EA                       Cilantro
1      20143381001_KG                  Roma Tomatoes
2      20179038001_KG                         Ginger
3      21004355001_EA          Garlic Bulbs, 3-count
4      20135581001_KG                Colossal Garlic
...               ...                            ...
10027  20311560003_EA  Bowl Noodle Soup, Hot & Spicy
10028     21088254_EA        Hot Buffalo Wings Sauce
10029     21003336_EA        Cookies & Cream Cake 6"
10030     21283361_EA   Muffins Double Chocolate
10031     20173399_EA                   Panty Liners

                                             description uom  pricing.price  \
0      Cilantro is the bunched leafy green from the c...  EA           0.67
1      Roma (or plum) tomatoes are egg-shaped  and na...  KG           0.59
2      Ginger (or gingerroot) has a tough tan skin an...  KG           0.82
3      <p>Don't forget to add Garlic Bulbs to your we...  EA           0.78
4      Garlic has a plump bulb (or head) of individua...  KG           1.08
...                                                  ...  ..            ...
10027                                                NaN  EA           1.14
10028  Get hot & spicy restaurant-style wings at home...  EA           4.00
10029                                                NaN  EA           6.23
10030                                                NaN  EA           4.42
10031  Certified organic cotton cover.  Plastic free....  EA           4.44

                                                   Image   Store
0      https://assets.shop.loblaws.ca/products/200918...  Farahs
1      https://assets.shop.loblaws.ca/products/201433...  Farahs
2      https://assets.shop.loblaws.ca/products/201790...  Farahs
3      https://assets.shop.loblaws.ca/products/210043...  Farahs
4      https://assets.shop.loblaws.ca/products/201355...  Farahs
...                                                  ...     ...
10027  https://assets.shop.loblaws.ca/products/203115...  Farahs
10028  https://assets.shop.loblaws.ca/products/210882...  Farahs
10029  https://assets.shop.loblaws.ca/products/210033...  Farahs
10030  https://assets.shop.loblaws.ca/products/212833...  Farahs
10031  https://assets.shop.loblaws.ca/products/201733...  Farahs

[10032 rows x 7 columns]
            productId                          title  \
0      20091825001_EA                       Cilantro
1      20143381001_KG                  Roma Tomatoes
2      20179038001_KG                         Ginger
3      21004355001_EA          Garlic Bulbs, 3-count
4      20135581001_KG                Colossal Garlic
...               ...                            ...
10027  20311560003_EA  Bowl Noodle Soup, Hot & Spicy
10028     21088254_EA        Hot Buffalo Wings Sauce
10029     21003336_EA        Cookies & Cream Cake 6"
10030     21283361_EA   Muffins Double Chocolate
10031     20173399_EA                   Panty Liners

                                             description uom  pricing.price  \
0      Cilantro is the bunched leafy green from the c...  EA           0.69
1      Roma (or plum) tomatoes are egg-shaped  and na...  KG           0.61
2      Ginger (or gingerroot) has a tough tan skin an...  KG           0.85
3      <p>Don't forget to add Garlic Bulbs to your we...  EA           0.81
4      Garlic has a plump bulb (or head) of individua...  KG           1.11
...                                                  ...  ..            ...
10027                                                NaN  EA           1.18
10028  Get hot & spicy restaurant-style wings at home...  EA           4.13
10029                                                NaN  EA           6.44
10030                                                NaN  EA           4.57
10031  Certified organic cotton cover.  Plastic free....  EA           4.59

                                                   Image      Store
0      https://assets.shop.loblaws.ca/products/200918...  No Frills
1      https://assets.shop.loblaws.ca/products/201433...  No Frills
2      https://assets.shop.loblaws.ca/products/201790...  No Frills
3      https://assets.shop.loblaws.ca/products/210043...  No Frills
4      https://assets.shop.loblaws.ca/products/201355...  No Frills
...                                                  ...        ...
10027  https://assets.shop.loblaws.ca/products/203115...  No Frills
10028  https://assets.shop.loblaws.ca/products/210882...  No Frills
10029  https://assets.shop.loblaws.ca/products/210033...  No Frills
10030  https://assets.shop.loblaws.ca/products/212833...  No Frills
10031  https://assets.shop.loblaws.ca/products/201733...  No Frills

[10032 rows x 7 columns]